name: Jack
version: 1.0.0
author: bittiez
main: US.bittiez.Jack.main
commands:
    Jack:
        description: Jack reload command
        usage: /Jack
permissions:
    Jack.respond:
        description: Jack will only listen to you if you have this permission