name: Jack
version: 1.0.0
author: bittiez
main: US.bittiez.Jack.main
api-version: 1.15
commands:
    Jack:
        description: Jack reload command
        usage: /Jack reload
permissions:
    Jack.respond:
        description: Jack will only listen to you if you have this permission
    Jack.reload:
        descriptiom: Will allow the use of /jack reload command to reload config.yml and chat.yml